#############################################################################
# Makefile for building: vGLsumtp
# Generated by qmake (3.1) (Qt 5.9.9)
# Project:  vGLsumtp.pro
# Template: subdirs
# Command: D:\Qt\Qt5.9.9\bin\qmake.exe -o Makefile vGLsumtp.pro -spec linux-arm-gnueabi-g++
#############################################################################

MAKEFILE      = Makefile

first: make_first
QMAKE         = D:\Qt\Qt5.9.9\bin\qmake.exe
DEL_FILE      = del
CHK_DIR_EXISTS= if not exist
MKDIR         = mkdir
COPY          = copy /y
COPY_FILE     = copy /y
COPY_DIR      = xcopy /s /q /y /i
INSTALL_FILE  = copy /y
INSTALL_PROGRAM = copy /y
INSTALL_DIR   = xcopy /s /q /y /i
QINSTALL      = D:\Qt\Qt5.9.9\bin\qmake.exe -install qinstall
QINSTALL_PROGRAM = D:\Qt\Qt5.9.9\bin\qmake.exe -install qinstall -exe
DEL_FILE      = del
SYMLINK       = $(QMAKE) -install ln -f -s
DEL_DIR       = rmdir
MOVE          = move
TAR           = 
COMPRESS      = 
DISTNAME      = vGLsumtp1.0.0
DISTDIR = D:\Project\vGLsumtp\.tmp\vGLsumtp1.0.0
SUBTARGETS    =  \
		sub-vGLsumtpMainFrame \
		sub-vGCore \
		sub-vGSetting \
		sub-vGTime


sub-vGLsumtpMainFrame-qmake_all:  FORCE
	@if not exist vGLsumtpMainFrame\ mkdir vGLsumtpMainFrame\ & if not exist vGLsumtpMainFrame\ exit 1
	cd vGLsumtpMainFrame\ && $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGLsumtpMainFrame\vGLsumtpMainFrame.pro -spec linux-arm-gnueabi-g++
	cd vGLsumtpMainFrame\ && $(MAKE) -f Makefile qmake_all
sub-vGLsumtpMainFrame: FORCE
	@if not exist vGLsumtpMainFrame\ mkdir vGLsumtpMainFrame\ & if not exist vGLsumtpMainFrame\ exit 1
	cd vGLsumtpMainFrame\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGLsumtpMainFrame\vGLsumtpMainFrame.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile
sub-vGLsumtpMainFrame-make_first: FORCE
	@if not exist vGLsumtpMainFrame\ mkdir vGLsumtpMainFrame\ & if not exist vGLsumtpMainFrame\ exit 1
	cd vGLsumtpMainFrame\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGLsumtpMainFrame\vGLsumtpMainFrame.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile 
sub-vGLsumtpMainFrame-all: FORCE
	@if not exist vGLsumtpMainFrame\ mkdir vGLsumtpMainFrame\ & if not exist vGLsumtpMainFrame\ exit 1
	cd vGLsumtpMainFrame\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGLsumtpMainFrame\vGLsumtpMainFrame.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile all
sub-vGLsumtpMainFrame-clean: FORCE
	@if not exist vGLsumtpMainFrame\ mkdir vGLsumtpMainFrame\ & if not exist vGLsumtpMainFrame\ exit 1
	cd vGLsumtpMainFrame\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGLsumtpMainFrame\vGLsumtpMainFrame.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile clean
sub-vGLsumtpMainFrame-distclean: FORCE
	@if not exist vGLsumtpMainFrame\ mkdir vGLsumtpMainFrame\ & if not exist vGLsumtpMainFrame\ exit 1
	cd vGLsumtpMainFrame\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGLsumtpMainFrame\vGLsumtpMainFrame.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile distclean
sub-vGLsumtpMainFrame-install_subtargets: FORCE
	@if not exist vGLsumtpMainFrame\ mkdir vGLsumtpMainFrame\ & if not exist vGLsumtpMainFrame\ exit 1
	cd vGLsumtpMainFrame\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGLsumtpMainFrame\vGLsumtpMainFrame.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile install
sub-vGLsumtpMainFrame-uninstall_subtargets: FORCE
	@if not exist vGLsumtpMainFrame\ mkdir vGLsumtpMainFrame\ & if not exist vGLsumtpMainFrame\ exit 1
	cd vGLsumtpMainFrame\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGLsumtpMainFrame\vGLsumtpMainFrame.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile uninstall
sub-vGCore-qmake_all:  FORCE
	@if not exist vGCore\ mkdir vGCore\ & if not exist vGCore\ exit 1
	cd vGCore\ && $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGCore\vGCore.pro -spec linux-arm-gnueabi-g++
	cd vGCore\ && $(MAKE) -f Makefile qmake_all
sub-vGCore: FORCE
	@if not exist vGCore\ mkdir vGCore\ & if not exist vGCore\ exit 1
	cd vGCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGCore\vGCore.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile
sub-vGCore-make_first: FORCE
	@if not exist vGCore\ mkdir vGCore\ & if not exist vGCore\ exit 1
	cd vGCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGCore\vGCore.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile 
sub-vGCore-all: FORCE
	@if not exist vGCore\ mkdir vGCore\ & if not exist vGCore\ exit 1
	cd vGCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGCore\vGCore.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile all
sub-vGCore-clean: FORCE
	@if not exist vGCore\ mkdir vGCore\ & if not exist vGCore\ exit 1
	cd vGCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGCore\vGCore.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile clean
sub-vGCore-distclean: FORCE
	@if not exist vGCore\ mkdir vGCore\ & if not exist vGCore\ exit 1
	cd vGCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGCore\vGCore.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile distclean
sub-vGCore-install_subtargets: FORCE
	@if not exist vGCore\ mkdir vGCore\ & if not exist vGCore\ exit 1
	cd vGCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGCore\vGCore.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile install
sub-vGCore-uninstall_subtargets: FORCE
	@if not exist vGCore\ mkdir vGCore\ & if not exist vGCore\ exit 1
	cd vGCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGCore\vGCore.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile uninstall
sub-vGSetting-qmake_all:  FORCE
	@if not exist vGSetting\ mkdir vGSetting\ & if not exist vGSetting\ exit 1
	cd vGSetting\ && $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGSetting\vGSetting.pro -spec linux-arm-gnueabi-g++
	cd vGSetting\ && $(MAKE) -f Makefile qmake_all
sub-vGSetting: FORCE
	@if not exist vGSetting\ mkdir vGSetting\ & if not exist vGSetting\ exit 1
	cd vGSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGSetting\vGSetting.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile
sub-vGSetting-make_first: FORCE
	@if not exist vGSetting\ mkdir vGSetting\ & if not exist vGSetting\ exit 1
	cd vGSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGSetting\vGSetting.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile 
sub-vGSetting-all: FORCE
	@if not exist vGSetting\ mkdir vGSetting\ & if not exist vGSetting\ exit 1
	cd vGSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGSetting\vGSetting.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile all
sub-vGSetting-clean: FORCE
	@if not exist vGSetting\ mkdir vGSetting\ & if not exist vGSetting\ exit 1
	cd vGSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGSetting\vGSetting.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile clean
sub-vGSetting-distclean: FORCE
	@if not exist vGSetting\ mkdir vGSetting\ & if not exist vGSetting\ exit 1
	cd vGSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGSetting\vGSetting.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile distclean
sub-vGSetting-install_subtargets: FORCE
	@if not exist vGSetting\ mkdir vGSetting\ & if not exist vGSetting\ exit 1
	cd vGSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGSetting\vGSetting.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile install
sub-vGSetting-uninstall_subtargets: FORCE
	@if not exist vGSetting\ mkdir vGSetting\ & if not exist vGSetting\ exit 1
	cd vGSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGSetting\vGSetting.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile uninstall
sub-vGTime-qmake_all:  FORCE
	@if not exist vGTime\ mkdir vGTime\ & if not exist vGTime\ exit 1
	cd vGTime\ && $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGTime\vGTime.pro -spec linux-arm-gnueabi-g++
	cd vGTime\ && $(MAKE) -f Makefile qmake_all
sub-vGTime: FORCE
	@if not exist vGTime\ mkdir vGTime\ & if not exist vGTime\ exit 1
	cd vGTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGTime\vGTime.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile
sub-vGTime-make_first: FORCE
	@if not exist vGTime\ mkdir vGTime\ & if not exist vGTime\ exit 1
	cd vGTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGTime\vGTime.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile 
sub-vGTime-all: FORCE
	@if not exist vGTime\ mkdir vGTime\ & if not exist vGTime\ exit 1
	cd vGTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGTime\vGTime.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile all
sub-vGTime-clean: FORCE
	@if not exist vGTime\ mkdir vGTime\ & if not exist vGTime\ exit 1
	cd vGTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGTime\vGTime.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile clean
sub-vGTime-distclean: FORCE
	@if not exist vGTime\ mkdir vGTime\ & if not exist vGTime\ exit 1
	cd vGTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGTime\vGTime.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile distclean
sub-vGTime-install_subtargets: FORCE
	@if not exist vGTime\ mkdir vGTime\ & if not exist vGTime\ exit 1
	cd vGTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGTime\vGTime.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile install
sub-vGTime-uninstall_subtargets: FORCE
	@if not exist vGTime\ mkdir vGTime\ & if not exist vGTime\ exit 1
	cd vGTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGTime\vGTime.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile uninstall

Makefile: vGLsumtp.pro ..\..\Qt\Qt5.9.9\mkspecs\linux-arm-gnueabi-g++\qmake.conf ..\..\Qt\Qt5.9.9\mkspecs\features\spec_pre.prf \
		..\..\Qt\Qt5.9.9\mkspecs\common\unix.conf \
		..\..\Qt\Qt5.9.9\mkspecs\common\linux.conf \
		..\..\Qt\Qt5.9.9\mkspecs\common\sanitize.conf \
		..\..\Qt\Qt5.9.9\mkspecs\common\gcc-base.conf \
		..\..\Qt\Qt5.9.9\mkspecs\common\gcc-base-unix.conf \
		..\..\Qt\Qt5.9.9\mkspecs\common\g++-base.conf \
		..\..\Qt\Qt5.9.9\mkspecs\common\g++-unix.conf \
		..\..\Qt\Qt5.9.9\mkspecs\qconfig.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_accessibility_support_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_bluetooth.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_bluetooth_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_bootstrap_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_charts.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_charts_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_concurrent.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_concurrent_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_core.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_core_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_dbus.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_dbus_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_devicediscovery_support_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_fb_support_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_fontdatabase_support_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_gamepad.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_gamepad_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_gui.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_gui_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_input_support_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_multimedia.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_multimedia_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_multimediawidgets.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_multimediawidgets_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_network.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_network_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_networkauth.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_networkauth_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_nfc.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_nfc_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_packetprotocol_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_printsupport.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_printsupport_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_purchasing.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_purchasing_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qml.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qml_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qmldebug_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qmldevtools_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qmltest.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qmltest_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quick.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quick_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quickcontrols2.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quickcontrols2_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quicktemplates2_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quickwidgets.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quickwidgets_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_remoteobjects.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_remoteobjects_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_repparser.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_repparser_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_script.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_script_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_scripttools.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_scripttools_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_scxml.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_scxml_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_sensors.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_sensors_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_serialbus.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_serialbus_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_serialport.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_serialport_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_service_support_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_sql.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_sql_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_svg.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_svg_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_testlib.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_testlib_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_texttospeech.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_texttospeech_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_theme_support_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_webchannel.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_webchannel_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_websockets.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_websockets_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_widgets.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_widgets_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_xml.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_xml_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_xmlpatterns.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_xmlpatterns_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_zlib_private.pri \
		..\..\Qt\Qt5.9.9\mkspecs\features\qt_functions.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\qt_config.prf \
		..\..\Qt\Qt5.9.9\mkspecs\linux-arm-gnueabi-g++\qmake.conf \
		..\..\Qt\Qt5.9.9\mkspecs\features\spec_post.prf \
		.qmake.stash \
		..\..\Qt\Qt5.9.9\mkspecs\features\exclusive_builds.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\toolchain.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\default_pre.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\resolve_config.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\default_post.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\warn_on.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\qmake_use.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\file_copies.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\testcase_targets.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\exceptions.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\yacc.prf \
		..\..\Qt\Qt5.9.9\mkspecs\features\lex.prf \
		vGLsumtp.pro
	$(QMAKE) -o Makefile vGLsumtp.pro -spec linux-arm-gnueabi-g++
..\..\Qt\Qt5.9.9\mkspecs\features\spec_pre.prf:
..\..\Qt\Qt5.9.9\mkspecs\common\unix.conf:
..\..\Qt\Qt5.9.9\mkspecs\common\linux.conf:
..\..\Qt\Qt5.9.9\mkspecs\common\sanitize.conf:
..\..\Qt\Qt5.9.9\mkspecs\common\gcc-base.conf:
..\..\Qt\Qt5.9.9\mkspecs\common\gcc-base-unix.conf:
..\..\Qt\Qt5.9.9\mkspecs\common\g++-base.conf:
..\..\Qt\Qt5.9.9\mkspecs\common\g++-unix.conf:
..\..\Qt\Qt5.9.9\mkspecs\qconfig.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_accessibility_support_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_bluetooth.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_bluetooth_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_bootstrap_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_charts.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_charts_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_concurrent.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_concurrent_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_core.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_core_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_dbus.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_dbus_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_devicediscovery_support_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_eventdispatcher_support_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_fb_support_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_fontdatabase_support_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_gamepad.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_gamepad_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_gui.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_gui_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_input_support_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_multimedia.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_multimedia_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_multimediawidgets.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_multimediawidgets_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_network.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_network_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_networkauth.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_networkauth_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_nfc.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_nfc_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_packetprotocol_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_printsupport.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_printsupport_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_purchasing.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_purchasing_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qml.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qml_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qmldebug_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qmldevtools_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qmltest.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_qmltest_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quick.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quick_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quickcontrols2.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quickcontrols2_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quicktemplates2_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quickwidgets.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_quickwidgets_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_remoteobjects.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_remoteobjects_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_repparser.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_repparser_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_script.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_script_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_scripttools.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_scripttools_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_scxml.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_scxml_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_sensors.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_sensors_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_serialbus.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_serialbus_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_serialport.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_serialport_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_service_support_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_sql.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_sql_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_svg.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_svg_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_testlib.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_testlib_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_texttospeech.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_texttospeech_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_theme_support_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_webchannel.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_webchannel_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_websockets.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_websockets_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_widgets.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_widgets_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_xml.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_xml_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_xmlpatterns.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_xmlpatterns_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\modules\qt_lib_zlib_private.pri:
..\..\Qt\Qt5.9.9\mkspecs\features\qt_functions.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\qt_config.prf:
..\..\Qt\Qt5.9.9\mkspecs\linux-arm-gnueabi-g++\qmake.conf:
..\..\Qt\Qt5.9.9\mkspecs\features\spec_post.prf:
.qmake.stash:
..\..\Qt\Qt5.9.9\mkspecs\features\exclusive_builds.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\toolchain.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\default_pre.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\resolve_config.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\default_post.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\warn_on.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\qmake_use.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\file_copies.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\testcase_targets.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\exceptions.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\yacc.prf:
..\..\Qt\Qt5.9.9\mkspecs\features\lex.prf:
vGLsumtp.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile vGLsumtp.pro -spec linux-arm-gnueabi-g++

qmake_all: sub-vGLsumtpMainFrame-qmake_all sub-vGCore-qmake_all sub-vGSetting-qmake_all sub-vGTime-qmake_all FORCE

make_first: sub-vGLsumtpMainFrame-make_first sub-vGCore-make_first sub-vGSetting-make_first sub-vGTime-make_first  FORCE
all: sub-vGLsumtpMainFrame-all sub-vGCore-all sub-vGSetting-all sub-vGTime-all  FORCE
clean: sub-vGLsumtpMainFrame-clean sub-vGCore-clean sub-vGSetting-clean sub-vGTime-clean  FORCE
distclean: sub-vGLsumtpMainFrame-distclean sub-vGCore-distclean sub-vGSetting-distclean sub-vGTime-distclean  FORCE
	-$(DEL_FILE) Makefile
	-$(DEL_FILE) .qmake.stash
install_subtargets: sub-vGLsumtpMainFrame-install_subtargets sub-vGCore-install_subtargets sub-vGSetting-install_subtargets sub-vGTime-install_subtargets FORCE
uninstall_subtargets: sub-vGLsumtpMainFrame-uninstall_subtargets sub-vGCore-uninstall_subtargets sub-vGSetting-uninstall_subtargets sub-vGTime-uninstall_subtargets FORCE

sub-vGLsumtpMainFrame-check:
	@if not exist vGLsumtpMainFrame\ mkdir vGLsumtpMainFrame\ & if not exist vGLsumtpMainFrame\ exit 1
	cd vGLsumtpMainFrame\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGLsumtpMainFrame\vGLsumtpMainFrame.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile check
sub-vGCore-check:
	@if not exist vGCore\ mkdir vGCore\ & if not exist vGCore\ exit 1
	cd vGCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGCore\vGCore.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile check
sub-vGSetting-check:
	@if not exist vGSetting\ mkdir vGSetting\ & if not exist vGSetting\ exit 1
	cd vGSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGSetting\vGSetting.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile check
sub-vGTime-check:
	@if not exist vGTime\ mkdir vGTime\ & if not exist vGTime\ exit 1
	cd vGTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGTime\vGTime.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile check
check: sub-vGLsumtpMainFrame-check sub-vGCore-check sub-vGSetting-check sub-vGTime-check

sub-vGLsumtpMainFrame-benchmark:
	@if not exist vGLsumtpMainFrame\ mkdir vGLsumtpMainFrame\ & if not exist vGLsumtpMainFrame\ exit 1
	cd vGLsumtpMainFrame\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGLsumtpMainFrame\vGLsumtpMainFrame.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile benchmark
sub-vGCore-benchmark:
	@if not exist vGCore\ mkdir vGCore\ & if not exist vGCore\ exit 1
	cd vGCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGCore\vGCore.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile benchmark
sub-vGSetting-benchmark:
	@if not exist vGSetting\ mkdir vGSetting\ & if not exist vGSetting\ exit 1
	cd vGSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGSetting\vGSetting.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile benchmark
sub-vGTime-benchmark:
	@if not exist vGTime\ mkdir vGTime\ & if not exist vGTime\ exit 1
	cd vGTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGTime\vGTime.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -f Makefile benchmark
benchmark: sub-vGLsumtpMainFrame-benchmark sub-vGCore-benchmark sub-vGSetting-benchmark sub-vGTime-benchmark
install:install_subtargets  FORCE

uninstall: uninstall_subtargets FORCE

FORCE:

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: sub-vGLsumtpMainFrame-distdir sub-vGCore-distdir sub-vGSetting-distdir sub-vGTime-distdir FORCE
	@if not exist $(DISTDIR) mkdir $(DISTDIR) & if not exist $(DISTDIR) exit 1
	$(COPY_FILE) --parents  $(DISTDIR)\

sub-vGLsumtpMainFrame-distdir: FORCE
	@if not exist vGLsumtpMainFrame\ mkdir vGLsumtpMainFrame\ & if not exist vGLsumtpMainFrame\ exit 1
	cd vGLsumtpMainFrame\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGLsumtpMainFrame\vGLsumtpMainFrame.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)\vGLsumtpMainFrame

sub-vGCore-distdir: FORCE
	@if not exist vGCore\ mkdir vGCore\ & if not exist vGCore\ exit 1
	cd vGCore\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGCore\vGCore.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)\vGCore

sub-vGSetting-distdir: FORCE
	@if not exist vGSetting\ mkdir vGSetting\ & if not exist vGSetting\ exit 1
	cd vGSetting\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGSetting\vGSetting.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)\vGSetting

sub-vGTime-distdir: FORCE
	@if not exist vGTime\ mkdir vGTime\ & if not exist vGTime\ exit 1
	cd vGTime\ && ( if not exist Makefile $(QMAKE) -o Makefile D:\Project\vGLsumtp\vGTime\vGTime.pro -spec linux-arm-gnueabi-g++ ) && $(MAKE) -e -f Makefile distdir DISTDIR=$(DISTDIR)\vGTime

